/* tslint:disable */
/* eslint-disable */
/**
 * Kloutit Clients API
 * Kloutit list of Client API calls
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

/**
 *
 * @export
 */
export enum KloutitEnvironment {
    development = 'development',
    production = 'production'
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    protected basePath: string;

    constructor(environment: KloutitEnvironment = KloutitEnvironment.production,
    protected axios: AxiosInstance = globalAxios,
    configuration?: Configuration) {
        if(configuration?.basePath) {
            this.basePath = configuration.basePath;
        } else {
            this.basePath = this.getBasePath(environment);
        }
    }

    /**
     * Get the base path based on the environment.
     * @param environment The environment ('development' or 'production').
     * @returns The base path for the API.
     */
    private getBasePath(environment: KloutitEnvironment): string {
        const basePaths = {
            development:  'https://dev.clients-api.kloutit.com',
            production: 'https://clients-api.kloutit.com'
        };

        return basePaths[environment];
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
}
